#pragma once
#ifndef CAMERA_STATUS
#define CAMERA_STATUS
#include <cinttypes>

#define BATTERY_PRESENT_ID 1
#define INTERNALBATTERYBARS_ID 2
#define OVERHEATING_ID 6
#define BUSY_ID 8
#define QUICK_CAPTURE_ID 9
#define ENCODING_ID 10
#define LCD_LOCK_ID 11
#define VIDEO_ENCODING_DURATION_ID 13
#define WIRELESS_CONNECTIONS_ENABLED_ID 17
#define PAIRING_STATE_ID 19
#define LAST_PAIRING_TYPE_ID 20
#define LAST_PAIRING_SUCESS_ID 21
#define WIFI_SCAN_STATE_ID 22
#define LAST_WIFI_SCAN_SUCESS_ID 23
#define WIFI_PROVISIONING_STATE_ID 24
#define REMOTE_VERSION_ID 26
#define REMOTE_CONNECTED_ID 27
#define CONNECTED_WIFI_SSID_ID 29
#define ACCESS_POINT_SSID_ID 30
#define CONNECTED_DEVICE_ID 31
#define PREVIEW_STREAM_ID 32
#define PRIMARY_STORAGE_ID 33
#define REMAINING_PHOTOS_ID 34
#define REMAINING_VIDEO_TIME_ID 35
#define PHOTOS_ID 38
#define VIDEOS_ID 39
#define OTA_ID 41
#define PENDING_FW_UPDATE_CANCEL_ID 42
#define LOCATE_ID 45
#define TIMELAPSE_INTERVAL_COUNTDOWN_ID 49
#define SD_CARD_REMAINING_ID 54
#define PREVIEW_STREAM_AVAILABLE_ID 55
#define WIFI_BARS_ID 56
#define ACTIVE_HILIGHTS_ID 58
#define TIME_SINCE_LAST_HILIGHT_ID 59
#define MINIMUM_STATUS_POLL_PREIOD_ID 60
#define LIVEVIEW_EXPOSURE_SELECT_MODE_ID 65
#define LIVEVIEW_Y_ID 66
#define LIVEVIEW_X_ID 67
#define GPS_LOCK_ID 68
#define AP_MODE_ID 69
#define INTERNAL_BATTERY_PERCENTAGE_ID 70
#define MICROPHONE_ACCESSORY_ID 74
#define ZOOM_LEVEL_ID 75
#define WIRELESS_BAND_ID 76
#define ZOOM_AVAILABLE_ID 77
#define MOBILE_FRIENDLY_ID 78
#define FTU_ID 79
#define _5GHZ_AVAILABLE_ID 81
#define READY_ID 82
#define OTA_CHANGED_ID 83
#define COLD_ID 85
#define ROTATION_ID 86
#define ZOOM_WHILE_ENCODING_ID 88
#define FLATMODE_ID 89
#define VIDEO_PRESET_ID 93
#define PHOTO_PRESET_ID 94
#define TIMELAPSE_PRESET_ID 95
#define PRESET_GROUP_ID 96
#define PRESET_ID 97
#define PRESET_MODIFIED_ID 98
#define REMAINING_LIVE_BURSTS_ID 99
#define LIVE_BURSTS_ID 100
#define CAPTURE_DELAY_ACTIVE_ID 101
#define MEDIA_MOD_STATE_ID 102
#define TIME_WARP_SPEED_ID 103
#define LINUX_CORE_ID 104
#define LENS_TYPE_ID 105
#define HINDSIGHT_ID 106

#endif