#pragma once
#ifndef CAMERAMODEL_GENERATED_H
#define CAMERAMODEL_GENERATED_H

#define MODEL_9_ID 1
#define MODEL_10_ID 2
#define MODEL_11_ID 4
#define MODEL_11_BLACK_ID 8
#define MODEL_12_BLACK_ID 16
#define MODEL_13_BLACK_ID 32
#define MODEL_MAX2_ID 64

#endif